### PR TITLE
Bcrypt password manager

### PR DESCRIPTION
**Pull request by mgrbyte**
@tseaver This provides a [bcrypt](https://pypi.python.org/pypi/bcrypt/2.0.0) password manager.

### CODE REVIEW

**Comment by tseaver** [comment]
@mgrbyte  Travis [bombs for `pypy`](https://travis-ci.org/zopefoundation/zope.password/jobs/82989011) because the `cffi` it provides is too old.  Can you suggest a workaround?

**Comment by mgrbyte** [comment]
We could do what bcrypt does for its travis builds:
https://github.com/pyca/bcrypt/blob/master/.travis.yml
https://github.com/pyca/bcrypt/tree/master/.travis

**Comment by mgrbyte** [comment]
Sorry, this is the relevant commit - seems they solved the issue of travis not having a late enough pypy being building their own and then overriding the default TOX env vars for python:
https://github.com/pyca/bcrypt/commit/15cc4edec22c455f467fa97bb27aa6bbb9deffb4

**Comment by mgedmin** [comment]
This is *excellent*.  I've long sighed about the lack of bcrypt support in zope auth modules.

Do you have any plans to make it usable with Zope 3 apps?  Because the current Zope 3 security architecture is
- let's stick the user-provided plaintext password in the browser session
- let's authenticate the plaintext password taken from the session on every request, during the traversal phase (after each traversal step even)

And paying the bcrypt cost for every request seems ... suboptimal.

**Comment by mgedmin** [comment]
Is there a PPA with pypy that we might use?  Travis CI [supports some PPAs](https://github.com/ansible/ansible/blob/a0920c06e1e5391b0a8c8441b76c178170476e70/.travis.yml#L8-L13) even with `sudo: false`.

What about other Zope packages that depend on zope.password and have PyPy enabled in their .travis.yml?  Will we have to add steps to install custom PyPy in each of their .travis.yml's?

When does Travis plan to upgrade their PyPy?  I think they roll out dev env upgrades every quarter?

**Comment by mgrbyte** [comment]
@mgedmin 
We have only one active zope3 app at work.
We've already changed that not to store plain text passwords in the session, or the cookie, and uses bcrypt auth iin a custom auth plugin.

I'm intending to use this as a replacement for AccessControl.AuthEncoding in an addon for Plone (dx.membrane).  The default password hashing algorithm there is SSHA (!)
I think it could be useful if people could configure bcrypt as the default.

**Comment by tseaver** [comment]
I don't want to go down the "install my own pypy" rabbit hole.  Until Travis updates to use a compatible `pypy`, let's make `bcrypt` a "soft" dependency, and do conditional imports.  E.g.:

```python
try:
    import bcrypt
except ImportError:
    bcrypt = None
...
if bcrypt is not None:

    class BCRYPTPasswordManager(PlainTextPasswordManager):
        ...
```

And document that using the `bcrypt` encoder requires installing `bcrypt` manually.

**Comment by mgrbyte** [comment]
@tseaver I updated the zpasswd script and narrative docs to make bcrypt the default (if installed),
in particular, the docs mentioned SSHA being the most secure, which is now not true.

 * Added missing ZCML utility registration (conditionals)
 * Added missing documentation for bcrypt manager.
 * Fixed tox.ini to not attempt installing bcrypt.
 * travis: install bcrypt for all but pypy*

**Comment by mgedmin** [comment]
LGTM.

**Pull request merged**
